# Generated by Django 6.0.6 on 2026-07-02 02:42

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('email_address', models.CharField(db_index=True, max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('is_locked', models.BooleanField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'UserAccount',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('email_address', models.CharField(db_index=True, max_length=255)),
                ('token_password', models.CharField(max_length=255)),
                ('requested_on', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('is_used', models.BooleanField()),
                ('is_expired', models.BooleanField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('user_account', models.ForeignKey(db_column='user_account_id', on_delete=django.db.models.deletion.RESTRICT, related_name='password_reset_request', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'PasswordResetRequest',
            },
        ),
        migrations.CreateModel(
            name='AuthenticationOTP',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('requested_on', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('is_approved', models.BooleanField()),
                ('is_expired', models.BooleanField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('user_account', models.ForeignKey(db_column='user_account_id', on_delete=django.db.models.deletion.RESTRICT, related_name='user_account', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'AuthenticationOTP',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.RESTRICT, related_name='user_profile', to='user_profile.profile')),
                ('user_account', models.ForeignKey(db_column='user_account_id', on_delete=django.db.models.deletion.RESTRICT, related_name='user_profile', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
