"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

#Load Environment Variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%dgi!s%+xh$=y-k(=+cx%2yp&t=kjt%5$j_o2miaofpqio^afb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'corsheaders',
    'apps.user_profile',
    'apps.organization',
    'apps.audit',
    'apps.authentication',
    'apps.authorization',
    'apps.ai_core',
    'apps.mcp'

]

GRAPHENE = {
    "SCHEMA": 'config.schema.schema'
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware", 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.ProjectMiddleware'
]

CORS_ALLOWED_ORIGINS = os.environ.get("ALLOWED_URLS", "").split(",")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get("DB_DEFAULT_ENGINE", "django.db.backends.sqlite"),
        'NAME': os.environ.get("DB_DEFAULT_NAME", "db_name"),
        'USER': os.environ.get("DB_DEFAULT_USERNAME", "username"),
        'PASSWORD': os.environ.get("DB_DEFAULT_PASSWORD", "password"),
        'HOST': os.environ.get("DB_DEFAULT_HOSTNAME", "localhost"),
        'PORT': os.environ.get("DB_DEFAULT_ROOT", "5432"),
    },
    'main': {
        'ENGINE': os.environ.get("DB_MAIN_ENGINE", "django.db.backends.sqlite"),
        'NAME': os.environ.get("DB_MAIN_NAME", "db_name"),
        'USER': os.environ.get("DB_MAIN_USERNAME", "username"),
        'PASSWORD': os.environ.get("DB_MAIN_PASSWORD", "password"),
        'HOST': os.environ.get("DB_MAIN_HOSTNAME", "localhost"),
        'PORT': os.environ.get("DB_MAIN_ROOT", "5432"),
    },
    'logs': {
        'ENGINE': os.environ.get("DB_LOG_ENGINE", "django.db.backends.sqlite"),
        'NAME': os.environ.get("DB_LOG_NAME", "db_name"),
        'USER': os.environ.get("DB_LOG_USERNAME", "username"),
        'PASSWORD': os.environ.get("DB_LOG_PASSWORD", "password"),
        'HOST': os.environ.get("DB_LOG_HOSTNAME", "localhost"),
        'PORT': os.environ.get("DB_LOG_ROOT", "5432"),
    }
}

DATABASE_ROUTERS = [
    "config.routers.DatabaseRouter"
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
