# Generated by Django 6.0.6 on 2026-06-21 09:16

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('user_account_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('request_id', models.UUIDField()),
                ('action', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('resource_id', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('user_agent', models.TextField()),
                ('status_code', models.CharField(max_length=255)),
                ('response_time_ms', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'AccessLog',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.UUIDField()),
                ('old_data', models.TextField()),
                ('new_data', models.TextField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'AuditLog',
            },
        ),
    ]
