// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blackboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blackboard";
  };
  "pages/login.tsx": {
    id: "pages/login";
    page: "/";
  };
  "pages/blackboard.tsx": {
    id: "pages/blackboard";
    page: "/blackboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/login": typeof import("./app/pages/login.tsx");
  "pages/blackboard": typeof import("./app/pages/blackboard.tsx");
};