# Generated by Django 6.0.5 on 2026-06-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0003_alter_userprofile_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
