# Generated by Django 6.0.6 on 2026-07-02 02:42

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.RESTRICT, related_name='user_organization', to='organization.organization')),
                ('user_account', models.ForeignKey(db_column='user_account_id', on_delete=django.db.models.deletion.RESTRICT, related_name='user_organization', to='authentication.useraccount')),
            ],
            options={
                'db_table': 'UserOrganization',
            },
        ),
    ]
