# Generated by Django 6.0.6 on 2026-07-02 02:42

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('api_key', models.TextField()),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'LLMProvider',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=255)),
                ('summary_sequence_index', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.RESTRICT, related_name='conversation', to='user_profile.profile')),
            ],
            options={
                'db_table': 'Conversation',
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=50)),
                ('content', models.TextField()),
                ('sequence', models.PositiveIntegerField(editable=False)),
                ('iteration', models.PositiveIntegerField(default=1, editable=False)),
                ('message_type', models.CharField(choices=[('normal', 'Normal'), ('summarized', 'Summarized'), ('context', 'context')], default='normal', max_length=50)),
                ('token_count', models.IntegerField(default=0)),
                ('is_active_iteration', models.BooleanField(db_default=True, default=True)),
                ('is_visible', models.BooleanField(db_default=True, default=True)),
                ('is_failed', models.BooleanField(db_default=False, default=False)),
                ('is_summarized', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_message', to='ai_core.conversation')),
            ],
            options={
                'db_table': 'ConversationMessage',
            },
        ),
        migrations.CreateModel(
            name='ConversationSetting',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_setting', to='ai_core.conversation')),
            ],
            options={
                'db_table': 'ConversationSetting',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_storage_link', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('conversation_message', models.ForeignKey(db_column='conversation_message_id', on_delete=django.db.models.deletion.CASCADE, related_name='message_attachment', to='ai_core.conversationmessage')),
            ],
            options={
                'db_table': 'MessageAttachments',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('conversational', 'Conversational'), ('tool', 'Tool'), ('rag', 'RAG'), ('react', 'ReAct')], default='conversational', max_length=50)),
                ('display_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(blank=True)),
                ('temperature', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('top_k', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('top_p', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_tokens', models.IntegerField(default=1024, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.RESTRICT, related_name='agent', to='user_profile.profile')),
            ],
            options={
                'db_table': 'Agent',
                'constraints': [models.CheckConstraint(condition=models.Q(('temperature__gte', 0.0), ('temperature__lte', 2.0)), name='temperature_agent_check_validator')],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence', 'iteration'), name='unique_message_sequence_iteration'),
        ),
        migrations.AddConstraint(
            model_name='conversationsetting',
            constraint=models.CheckConstraint(condition=models.Q(('temperature__gte', 0.0), ('temperature__lte', 2.0)), name='temperature_setting_check_validator'),
        ),
    ]
