# Generated by Django 6.0.4 on 2026-05-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0002_profile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles', to='system_app.profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='system_app.user'),
        ),
    ]
