# Generated by Django 6.0.6 on 2026-07-02 02:42

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(db_default=models.Func(function='uuidv7'), primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('middle_initial', models.CharField(max_length=255, null=True)),
                ('prefix_name', models.CharField(max_length=255, null=True)),
                ('suffix_name', models.CharField(max_length=255, null=True)),
                ('email_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
